### ISSUE TITLE
Вопрос по задаче контеста (уже завершен) (offtop)

### ISSUE THREAD

**Issue by kartollika** [Voudy/code_guide#5]
**_Условие:_** 
> Задано целое число n. Вам необходимо найти количество таких чисел x, что `x ≤ n` и x — степень двойки. При этом `0 <= n <= 10^15`

**_Вопрос:_** 
> Что я упускаю, что система выдает мне WA?

```Java
static int calc() {
        Scanner scanner = new Scanner(System.in);
        double n = scanner.nextDouble();
        if (n == 0) {
            return 0;
        }
        return (int) Math.floor(Math.log(n) / Math.log(2)) + 1;
}
```

**Comment by kartollika** [comment]
Забавно, что падает оно на 26 тесте :thinking:

**Comment by Voudy** [comment]
А ты проверяешь случаи когда `n` и есть степень `2`?

Так же возможно потеря точности из-за работы с `double`, если время работы не критично, то можно использовать бинарный поиск по степеням `2`.

**Comment by Voudy** [comment]
Если больше нет вопросов, то закрой issue
