### ISSUE TITLE
Kotlin koans DONE

### ISSUE THREAD

**Issue by kartollika** [Voudy/code_guide#7]
Зарашил курс в темный и холодный вечер
Жаль, что сертификат не выдается только :cactus: 

![45/45](https://pp.userapi.com/c845522/v845522826/1eb5c/HLdrpLM2bvk.jpg)

![Неа, не выдается он](https://pp.userapi.com/c847017/v847017826/190b1/2Rvq3eSZZkI.jpg)

UPD: ну еще и ссылка прилагается https://stepik.org/users/35930535

**Comment by ImmortalTurtle** [comment]
Гуд джоб :+1: Обновил рейтинг
